# Credentials in ~/.crowdin.yml
# Or with env variable
# "api_token_env" : CROWDIN_API_TOKEN

# -----------------------------------------------
"project_id" : "630030"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

# -----------------------------------------------
# File structure in Crowdin
"preserve_hierarchy": true

# https://support.crowdin.com/configuration-file/
files: [{
    "source" : "locales/english.*",
    "translation" : "locales/%osx_locale%.%file_extension%",
    # OSX-locale
    # https://developer.crowdin.com/language-codes/
    "translation_replace": {
        "/ar." : "/arabic.",
        "/cs." : "/czech.",
        "/de." : "/german.",
        "/es." : "/spanish.",
        "/fr." : "/french.",
        "/he." : "/hebrew.",
        "/hi." : "/hindi.",
        "/id." : "/indonesian.",
        "/it." : "/italian.",
        "/ja." : "/japanese.",
        "/ko." : "/korean.",
        "/ms." : "/malay.",
        "/nl." : "/dutch.",
        "/pl." : "/polish.",
        "/pt." : "/portuguese.",
        "/ru." : "/russian.",
        "/sv." : "/swedish.",
        "/sv." : "/swedish.",
        "/th." : "/thai.",
        "/tr." : "/turkish.",
        "/vi." : "/vietnamese.",
        "/zh-Hans." : "/simplified-chinese.",
    },

    # ---------------------------------------------
    # Export To Crowdin
    # ---------------------------------------------
    # "update_option" : "update_as_unapproved",
    # "update_option" : "update_without_changes",
    # "type" : "",
    # "dest" : "",

    # "excluded_target_languages": ["zh_Hant"],

    # ---------------------------------------------
    # Import From Crowdin
    # ---------------------------------------------
    # "skip_untranslated_strings": true,
    "skip_untranslated_files": false,
    "export_only_approved": false,
    "content_segmentation" : 0,
}]

# targets: [{
#     name: "yml",
#     files: [{
#         file: "targets/%language%.xml",
#         sources: [ "locales/english.strings" ],
#     }]
# }]