# Credentials in ~/.crowdin.yml
# Or with env variable
# "api_token_env" : CROWDIN_API_TOKEN

# https://developer.crowdin.com/language-codes/

project_id: "630030"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "/locales/english.*"
    translation: "/locales/%osx_locale%.%file_extension%"
    translation_replace:
      "/ar.": "/arabic."
      "/cs.": "/czech."
      "/de.": "/german."
      "/es.": "/spanish."
      "/fr.": "/french."
      "/he.": "/hebrew."
      "/hi.": "/hindi."
      "/id.": "/indonesian."
      "/it.": "/italian."
      "/ja.": "/japanese."
      "/ko.": "/korean."
      "/ms.": "/malay."
      "/nl.": "/dutch."
      "/pl.": "/polish."
      "/pt.": "/portuguese."
      "/ru.": "/russian."
      "/sv.": "/swedish."
      "/th.": "/thai."
      "/tr.": "/turkish."
      "/vi.": "/vietnamese."
      "/zh-Hans.": "/simplified-chinese."
    skip_untranslated_files: false
    export_only_approved: false
    content_segmentation: 0
