# Credentials in ~/.crowdin.yml
# Or with env variable
# "api_token_env" : CROWDIN_API_TOKEN

# -----------------------------------------------
"project_id" : "630030"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

# -----------------------------------------------
# File structure in Crowdin
"preserve_hierarchy": true

# https://support.crowdin.com/configuration-file/
files: [{
    "source" : "*/english.*",
    "translation" : "%original_path%/%osx_locale%.%file_extension%",
    # https://developer.crowdin.com/language-codes/
    "translation_replace": {
        "/zh-Hans." : "/chinese-simplified.",
        "/fr." : "/french.",
        "/de." : "/german.",
        "/hi." : "/hindi.",
        "/it." : "/italian.",
        "/ja." : "/japanese.",
        "/ko." : "/korean.",
        "/pl." : "/polish.",
        "/pt." : "/portuguese.",
        "/ru." : "/russian.",
        "/es." : "/spanish.",
        "/th." : "/thai.",
        "/tr." : "/turkish."
    },

    # ---------------------------------------------
    # Export To Crowdin
    # ---------------------------------------------
    # "update_option" : "",
    # "type" : "",
    # "dest" : "",

    # "excluded_target_languages": ["zh_Hant"],

    # ---------------------------------------------
    # Import From Crowdin
    # ---------------------------------------------
    "skip_untranslated_strings": true,
    "export_only_approved": false,
    "content_segmentation" : 0,
}]

# targets: [{
#     name: "yml",
#     files: [{
#         file: "targets/%language%.xml",
#         sources: [ "locales/english.strings" ],
#     }]
# }]